
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
            path: ./README.md
      - name: output the message on actions result
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.package.outputs.content }}