
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user root
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name : Affiche le répertoire
        run: ls -l

      - name : Ma vache affiche mon readme 
        run: cat README.md | cowsay